<h1>CREDIT CARD FRAUD DETECTION</h1>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('fraudTrain.csv')

In [3]:
df.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1325376018,36.011293,-82.048315,0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1325376044,49.159047,-118.186462,0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1325376051,43.150704,-112.154481,0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1325376076,47.034331,-112.561071,0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1325376186,38.674999,-78.632459,0

<h3>PREPROCESSING</h3>

In [5]:
df.columns

Index(['Unnamed: 0', 'trans_date_trans_time', 'cc_num', 'merchant', 'category',
       'amt', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip',
       'lat', 'long', 'city_pop', 'job', 'dob', 'trans_num', 'unix_time',
       'merch_lat', 'merch_long', 'is_fraud'],
      dtype='object')

In [8]:
df.drop(columns=['Unnamed: 0','cc_num', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip','dob', 'trans_num','trans_date_trans_time' ],inplace=True)

In [9]:
df

,merchant,category,amt,lat,long,city_pop,job,unix_time,merch_lat,merch_long,is_fraud
0,"fraud_Rippin, Kub and Mann",misc_net,4.97,36.0788,-81.1781,3495,"Psychologist, counselling",1325376018,36.011293,-82.048315,0
1,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,48.8878,-118.2105,149,Special educational needs teacher,1325376044,49.159047,-118.186462,0
2,fraud_Lind-Buckridge,entertainment,220.11,42.1808,-112.2620,4154,Nature conservation officer,1325376051,43.150704,-112.154481,0
3,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,46.2306,-112.1138,1939,Patent attorney,1325376076,47.034331,-112.561071,0
4,fraud_Keeling-Crist,misc_pos,41.96,38.4207,-79.4629,99,Dance movement psychotherapist,1325376186,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...
1296670,fraud_Reichel Inc,entertainment,15.56,37.7175,-112.4777,258,Geoscientist,1371816728,36.841266,-111.690765,0
1296671,fraud_Abernathy and Sons,food_dining,51.70,39.2667,-77.5101,100,"Production assistant, television",1371816739,38.906881,-78.246528,0
1296672,fraud_Stiedemann Ltd,food_dining,105.93,32.9396,-105.8189,899,Naval architect,1371816752,33.619513,-105.130529,0
1296673,"fraud_Reinger, Weissnat and Strosin",food_dining,74.90,43.3526,-102.5411,1126,Volunteer coordinator,1371816816,42.788940,-103.241160,0
1296674,"fraud_Langosh, Wintheiser and Hyatt",food_dining,4.30,45.8433,-113.8748,218,"Therapist, horticultural",1371816817,46.565983,-114.186110,0

In [10]:
df.dropna()

,merchant,category,amt,lat,long,city_pop,job,unix_time,merch_lat,merch_long,is_fraud
0,"fraud_Rippin, Kub and Mann",misc_net,4.97,36.0788,-81.1781,3495,"Psychologist, counselling",1325376018,36.011293,-82.048315,0
1,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,48.8878,-118.2105,149,Special educational needs teacher,1325376044,49.159047,-118.186462,0
2,fraud_Lind-Buckridge,entertainment,220.11,42.1808,-112.2620,4154,Nature conservation officer,1325376051,43.150704,-112.154481,0
3,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,46.2306,-112.1138,1939,Patent attorney,1325376076,47.034331,-112.561071,0
4,fraud_Keeling-Crist,misc_pos,41.96,38.4207,-79.4629,99,Dance movement psychotherapist,1325376186,38.674999,-78.632459,0
...,...,...,...,...,...,...,...,...,...,...,...
1296670,fraud_Reichel Inc,entertainment,15.56,37.7175,-112.4777,258,Geoscientist,1371816728,36.841266,-111.690765,0
1296671,fraud_Abernathy and Sons,food_dining,51.70,39.2667,-77.5101,100,"Production assistant, television",1371816739,38.906881,-78.246528,0
1296672,fraud_Stiedemann Ltd,food_dining,105.93,32.9396,-105.8189,899,Naval architect,1371816752,33.619513,-105.130529,0
1296673,"fraud_Reinger, Weissnat and Strosin",food_dining,74.90,43.3526,-102.5411,1126,Volunteer coordinator,1371816816,42.788940,-103.241160,0
1296674,"fraud_Langosh, Wintheiser and Hyatt",food_dining,4.30,45.8433,-113.8748,218,"Therapist, horticultural",1371816817,46.565983,-114.186110,0

In [14]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()
df["merchant"] = encoder.fit_transform(df["merchant"])
df["category"] = encoder.fit_transform(df["category"])
df["job"] = encoder.fit_transform(df["job"])

In [22]:
x = df.iloc[:-1, :-1]  # Exclude the last row and last column for x
y = df.iloc[:-1, -1]   # Exclude the last row, but only select the last column for y

In [23]:
x

,merchant,category,amt,lat,long,city_pop,job,unix_time,merch_lat,merch_long
0,514,8,4.97,36.0788,-81.1781,3495,370,1325376018,36.011293,-82.048315
1,241,4,107.23,48.8878,-118.2105,149,428,1325376044,49.159047,-118.186462
2,390,0,220.11,42.1808,-112.2620,4154,307,1325376051,43.150704,-112.154481
3,360,2,45.00,46.2306,-112.1138,1939,328,1325376076,47.034331,-112.561071
4,297,9,41.96,38.4207,-79.4629,99,116,1325376186,38.674999,-78.632459
...,...,...,...,...,...,...,...,...,...,...
1296669,598,9,37.38,41.4972,-98.7858,509,311,1371816696,41.728638,-99.039660
1296670,499,0,15.56,37.7175,-112.4777,258,215,1371816728,36.841266,-111.690765
1296671,2,1,51.70,39.2667,-77.5101,100,360,1371816739,38.906881,-78.246528
1296672,599,1,105.93,32.9396,-105.8189,899,308,1371816752,33.619513,-105.130529
1296673,509,1,74.90,43.3526,-102.5411,1126,485,1371816816,42.788940,-103.241160

In [24]:
y

0          0
1          0
2          0
3          0
4          0
          ..
1296669    0
1296670    0
1296671    0
1296672    0
1296673    0
Name: is_fraud, Length: 1296674, dtype: int64

<H3>DATA SPLITING AND MODEL FITTING</H3>

In [25]:
from sklearn.linear_model import LogisticRegression

In [26]:
lr=LogisticRegression()

In [27]:
from sklearn.model_selection import train_test_split

In [35]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [36]:
xtrain.shape

(1037339, 10)

In [37]:
xtest.shape

(259335, 10)

In [38]:
lr.fit(xtrain,ytrain)

LogisticRegression()

In [39]:
pred=lr.predict(xtest)

In [40]:
from sklearn.metrics import accuracy_score

acc=accuracy_score(pred,ytest)

In [41]:
print(acc)

0.9941774153122409

<H3>TESTING ON TEST DATA</H3>

In [42]:
df2=pd.read_csv('fraudTest.csv')

In [43]:
df2.drop(columns=['Unnamed: 0','cc_num', 'first', 'last', 'gender', 'street', 'city', 'state', 'zip','dob', 'trans_num','trans_date_trans_time' ],inplace=True)

In [44]:
encoder = LabelEncoder()
df2["merchant"] = encoder.fit_transform(df2["merchant"])
df2["category"] = encoder.fit_transform(df2["category"])
df2["job"] = encoder.fit_transform(df2["job"])

In [45]:
x1= df2.iloc[:-1, :-1]  # Exclude the last row and last column for x
y1 = df2.iloc[:-1, -1]   # Exclude the last row, but only select the last column for y

In [49]:
x1.shape

(555718, 10)

In [50]:
y1.shape

(555718,)

In [46]:
test_res=lr.predict(x1)

In [47]:
acc2=accuracy_score(test_res,y1)

In [48]:
print(acc2)

0.9961401286263897

<H3>ACCURACY ACHIEVED : 99%</H3>

In [51]:
x.head()

,merchant,category,amt,lat,long,city_pop,job,unix_time,merch_lat,merch_long
0,514,8,4.97,36.0788,-81.1781,3495,370,1325376018,36.011293,-82.048315
1,241,4,107.23,48.8878,-118.2105,149,428,1325376044,49.159047,-118.186462
2,390,0,220.11,42.1808,-112.2620,4154,307,1325376051,43.150704,-112.154481
3,360,2,45.00,46.2306,-112.1138,1939,328,1325376076,47.034331,-112.561071
4,297,9,41.96,38.4207,-79.4629,99,116,1325376186,38.674999,-78.632459

In [ ]:
import tkinter as tk
from tkinter import messagebox
import pandas as pd  # Assuming you have pandas for data manipulation


# Function to handle button click and predict fraud
def check_fraud():
    # Get values from entry widgets
    merchant = int(entry_merchant.get())
    category = int(entry_category.get())
    amt = float(entry_amt.get())
    lat = float(entry_lat.get())
    long = float(entry_long.get())
    city_pop = int(entry_city_pop.get())
    job = int(entry_job.get())
    unix_time = int(entry_unix_time.get())
    merch_lat = float(entry_merch_lat.get())
    merch_long = float(entry_merch_long.get())

    # Create a DataFrame with the input data
    input_data = pd.DataFrame({
        'merchant': [merchant],
        'category': [category],
        'amt': [amt],
        'lat': [lat],
        'long': [long],
        'city_pop': [city_pop],
        'job': [job],
        'unix_time': [unix_time],
        'merch_lat': [merch_lat],
        'merch_long': [merch_long]
    })

    # Call the function to predict fraud (replace 'predict_fraud' with your actual prediction function)
    is_fraud =lr.predict(input_data)

    # Display the result
    if is_fraud == 1:
        result_text.set("This transaction is flagged as FRAUD!")
    else:
        result_text.set("This transaction is not fraudulent.")

# Create the main window
root = tk.Tk()
root.title("Credit Card Fraud Detection")

# Create entry widgets
labels = ['Merchant', 'Category', 'Amount', 'Latitude', 'Longitude', 'City Population', 'Job', 'Unix Time',
          'Merchant Latitude', 'Merchant Longitude']

for i, label_text in enumerate(labels):
    tk.Label(root, text=label_text).grid(row=i, column=0, sticky='e')

# Create entry widgets
entry_merchant = tk.Entry(root)
entry_category = tk.Entry(root)
entry_amt = tk.Entry(root)
entry_lat = tk.Entry(root)
entry_long = tk.Entry(root)
entry_city_pop = tk.Entry(root)
entry_job = tk.Entry(root)
entry_unix_time = tk.Entry(root)
entry_merch_lat = tk.Entry(root)
entry_merch_long = tk.Entry(root)

# Arrange entry widgets in a grid
entries = [entry_merchant, entry_category, entry_amt, entry_lat, entry_long, entry_city_pop, entry_job,
           entry_unix_time, entry_merch_lat, entry_merch_long]

for i, entry_widget in enumerate(entries):
    entry_widget.grid(row=i, column=1)

# Create a button to check fraud
check_button = tk.Button(root, text="Check Fraud", command=check_fraud)
check_button.grid(row=len(labels), column=0, columnspan=2)

# Create a label to display the result
result_text = tk.StringVar()
result_label = tk.Label(root, textvariable=result_text, font=('Helvetica', 12), fg='red')
result_label.grid(row=len(labels) + 1, column=0, columnspan=2)

# Start the Tkinter event loop
root.mainloop()